In [2]:
import pandas as pd
df=pd.read_csv(r"weather.csv")
print(df)
type(df)

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

pandas.core.frame.DataFrame

In [4]:
weather_data=[['1/1/2017',32,6,20,'Rain'],
              ['1/2/2017', 35,7 ,30 ,'Sunny']  ,
             ['1/3/2017', 28,2,45, 'Snow'],
             ['1/4/2017',24 ,7,40  , 'Snow'],
             ['1/5/2017',32,4, 35 ,  'Rain'],
             ['1/6/2017',31,2, 20 ,'Sunny']
             ]
df1=pd.DataFrame(weather_data,columns=['day','temperature','windspeed'  ,'humidity'  ,'event'])
df1

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

## Working on Rows and Columns

### to get the shape of the table/database

In [5]:
print(df.shape)

(6, 5)

In [7]:
print(df.columns)

Index(['day', 'temperature', 'windspeed', 'humidity', 'event'], dtype='object')

In [9]:
df.head()  #displays first 5

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain

In [10]:
df.head(3) #displays first 3

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow

In [11]:
df.tail() #displays last 5

        day  temperature  windspeed  humidity  event
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [12]:
df.tail(2) #display last 2

        day  temperature  windspeed  humidity  event
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [20]:
df.sample() #random 1 sample

        day  temperature  windspeed  humidity event
0  1/1/2017           32          6        20  Rain

In [21]:
df.sample(2) #random 2 sample

        day  temperature  windspeed  humidity event
2  1/3/2017           28          2        45  Snow
3  1/4/2017           24          7        40  Snow

In [29]:
df.day #display a particular column

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [28]:
df['day'] #display a particular column

0    1/1/2017
1    1/2/2017
2    1/3/2017
3    1/4/2017
4    1/5/2017
5    1/6/2017
Name: day, dtype: object

In [31]:
df[['day']] #display a particular column where double [] is for multiple values/columns

        day
0  1/1/2017
1  1/2/2017
2  1/3/2017
3  1/4/2017
4  1/5/2017
5  1/6/2017

In [32]:
df[['day','event']]

        day  event
0  1/1/2017   Rain
1  1/2/2017  Sunny
2  1/3/2017   Snow
3  1/4/2017   Snow
4  1/5/2017   Rain
5  1/6/2017  Sunny

In [33]:
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [36]:
df.temperature.describe() #describes a  particuar column

count     6.000000
mean     30.333333
std       3.829708
min      24.000000
25%      28.750000
50%      31.500000
75%      32.000000
max      35.000000
Name: temperature, dtype: float64

In [37]:
df.event.describe()

count        6
unique       3
top       Rain
freq         2
Name: event, dtype: object

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          6 non-null      object
 1   temperature  6 non-null      int64
 2   windspeed    6 non-null      int64
 3   humidity     6 non-null      int64
 4   event        6 non-null      object
dtypes: int64(3), object(2)
memory usage: 368.0+ bytes

In [39]:
df.iloc[2,4] #position based indexing

'Snow'

In [40]:
df.loc[2,'event'] #label based indexing

'Snow'

In [41]:
df.loc[2,'humidity']

45

## Minimal Operations

In [47]:
print(max(df.temperature)) #prints max temp

35

In [50]:
df['temperature'].max()

35

In [51]:
print(min(df.temperature)) #prints min temp

24

In [52]:
df['temperature'].min()

24

In [53]:
df['temperature'].std() #standard deviation

3.8297084310253524

In [56]:
df.temperature.mean() #mean

30.333333333333332

In [57]:
df.temperature  == df.temperature.max()  #comparision in terms of true and false  with the maximum value

0    False
1     True
2    False
3    False
4    False
5    False
Name: temperature, dtype: bool

In [58]:
df.temperature  == df.temperature.min()  #comparision in terms of true and false  with the minimum value

0    False
1    False
2    False
3     True
4    False
5    False
Name: temperature, dtype: bool

In [59]:
df[df.temperature  == df.temperature.max() ] #select rows which has max temp

        day  temperature  windspeed  humidity  event
1  1/2/2017           35          7        30  Sunny

In [60]:
df.day[df.temperature  == df.temperature.max() ]  #select only day column which has max temp

1    1/2/2017
Name: day, dtype: object

In [62]:
df.index #starting ad ending oins

RangeIndex(start=0, stop=6, step=1)

In [63]:
df

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [65]:
df.set_index('day') #doesnt modify the original data frame

          temperature  windspeed  humidity  event
day
1/1/2017           32          6        20   Rain
1/2/2017           35          7        30  Sunny
1/3/2017           28          2        45   Snow
1/4/2017           24          7        40   Snow
1/5/2017           32          4        35   Rain
1/6/2017           31          2        20  Sunny

In [66]:
df.set_index('day',inplace=True)  #mdify the original data frame

In [67]:
df.reset_index(inplace=True)

In [68]:
df

        day  temperature  windspeed  humidity  event
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
2  1/3/2017           28          2        45   Snow
3  1/4/2017           24          7        40   Snow
4  1/5/2017           32          4        35   Rain
5  1/6/2017           31          2        20  Sunny

In [73]:
df.sort_values(['windspeed']) #sort the values in ascending values

        day  temperature  windspeed  humidity  event
2  1/3/2017           28          2        45   Snow
5  1/6/2017           31          2        20  Sunny
4  1/5/2017           32          4        35   Rain
0  1/1/2017           32          6        20   Rain
1  1/2/2017           35          7        30  Sunny
3  1/4/2017           24          7        40   Snow

In [74]:
df.sort_values(['windspeed'],ascending=False)

        day  temperature  windspeed  humidity  event
1  1/2/2017           35          7        30  Sunny
3  1/4/2017           24          7        40   Snow
0  1/1/2017           32          6        20   Rain
4  1/5/2017           32          4        35   Rain
2  1/3/2017           28          2        45   Snow
5  1/6/2017           31          2        20  Sunny